import type { CollectionConfig } from "payload"
import {
  currencyCode,
  historyAccess,
  immutableHistoryFields,
  minorUnits,
  newHistoryKey,
  positiveInteger,
  preserveStripeIdentifiers,
  validatePaymentTotals,
} from "./history"

export const Payments: CollectionConfig = {
  slug: "payments",
  admin: {
    group: "Registration & payments",
    useAsTitle: "paymentKey",
    defaultColumns: [
      "submission",
      "attemptNumber",
      "status",
      "amountExpected",
      "currency",
      "livemode",
      "createdAt",
    ],
    description:
      "One record per checkout attempt. Retrying checkout creates another attempt, while Stripe retries reuse the same payment key.",
  },
  access: historyAccess,
  timestamps: true,
  versions: { maxPerDoc: 0 },
  indexes: [{ fields: ["submission", "attemptNumber"], unique: true }],
  hooks: {
    beforeValidate: [validatePaymentTotals],
    beforeChange: [
      immutableHistoryFields([
        "paymentKey",
        "submission",
        "attemptNumber",
        "provider",
        "amountExpected",
        "currency",
        "livemode",
        "createdAt",
      ]),
      preserveStripeIdentifiers,
    ],
  },
  fields: [
    {
      name: "paymentKey",
      type: "text",
      required: true,
      unique: true,
      index: true,
      defaultValue: newHistoryKey,
      admin: {
        description: "Persisted Stripe idempotency key for this attempt.",
      },
    },
    {
      name: "submission",
      type: "relationship",
      relationTo: "form-submissions",
      required: true,
      index: true,
    },
    {
      name: "attemptNumber",
      type: "number",
      required: true,
      min: 1,
      defaultValue: 1,
      validate: positiveInteger,
    },
    {
      name: "provider",
      type: "select",
      required: true,
      defaultValue: "stripe",
      options: ["stripe"],
    },
    {
      name: "livemode",
      label: "Live payment",
      type: "checkbox",
      required: true,
      defaultValue: false,
      index: true,
      admin: { description: "False identifies Stripe test/sandbox records." },
    },
    {
      name: "status",
      type: "select",
      required: true,
      defaultValue: "pending",
      index: true,
      options: [
        "pending",
        "processing",
        "succeeded",
        "failed",
        "expired",
        "cancelled",
        "partially_refunded",
        "refunded",
      ],
    },
    {
      name: "amountExpected",
      label: "Amount due (cents)",
      type: "number",
      required: true,
      min: 0,
      validate: minorUnits,
    },
    {
      name: "amountReceived",
      label: "Amount received (cents)",
      type: "number",
      required: true,
      defaultValue: 0,
      min: 0,
      validate: minorUnits,
    },
    {
      name: "amountRefunded",
      label: "Amount refunded (cents)",
      type: "number",
      required: true,
      defaultValue: 0,
      min: 0,
      validate: minorUnits,
    },
    {
      name: "currency",
      type: "text",
      required: true,
      defaultValue: "usd",
      validate: currencyCode,
    },
    {
      name: "stripe",
      type: "group",
      fields: [
        { name: "checkoutSessionId", type: "text", unique: true, index: true },
        { name: "paymentIntentId", type: "text", unique: true, index: true },
        { name: "latestChargeId", type: "text", index: true },
        { name: "customerId", type: "text", index: true },
        { name: "accountId", type: "text" },
        { name: "checkoutExpiresAt", type: "date" },
        { name: "receiptUrl", type: "text" },
        { name: "paymentMethodType", type: "text" },
      ],
    },
    { name: "succeededAt", type: "date" },
    { name: "failedAt", type: "date" },
    { name: "expiredAt", type: "date" },
    { name: "cancelledAt", type: "date" },
    {
      name: "failure",
      type: "group",
      fields: [
        { name: "code", type: "text" },
        { name: "declineCode", type: "text" },
        {
          name: "message",
          type: "textarea",
          maxLength: 500,
          admin: {
            description:
              "Sanitized diagnostic; never save credentials or full card data.",
          },
        },
      ],
    },
    {
      name: "refunds",
      type: "array",
      fields: [
        { name: "stripeRefundId", type: "text", required: true },
        {
          name: "amount",
          label: "Refund amount (cents)",
          type: "number",
          required: true,
          min: 0,
          validate: minorUnits,
        },
        {
          name: "status",
          type: "select",
          required: true,
          options: [
            "pending",
            "requires_action",
            "succeeded",
            "failed",
            "canceled",
          ],
        },
        { name: "reason", type: "text" },
        { name: "createdAt", type: "date", required: true },
        { name: "failureReason", type: "text" },
      ],
    },
    {
      name: "dispute",
      type: "group",
      fields: [
        { name: "stripeDisputeId", type: "text" },
        { name: "status", type: "text" },
        { name: "reason", type: "text" },
        {
          name: "amount",
          label: "Disputed amount (cents)",
          type: "number",
          min: 0,
          validate: minorUnits,
        },
        { name: "updatedAt", type: "date" },
      ],
    },
    {
      name: "processingLock",
      type: "group",
      admin: { hidden: true },
      fields: [
        { name: "token", type: "text" },
        { name: "until", type: "date" },
      ],
    },
    {
      name: "events",
      type: "join",
      collection: "payment-events",
      on: "payment",
    },
  ],
}
