/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PayloadRouteImport } from './routes/_payload'
import { Route as ArchivesRouteImport } from './routes/archives'
import { Route as HallOfFameRouteImport } from './routes/hall-of-fame'
import { Route as LocalLeaguesRouteImport } from './routes/local-leagues'
import { Route as MotelRouteImport } from './routes/motel'
import { Route as PitcherClassificationRouteImport } from './routes/pitcher-classification'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as TournamentsRouteImport } from './routes/tournaments'
import { Route as UmpireRouteImport } from './routes/umpire'
import { Route as UmpiresRouteImport } from './routes/umpires'
import { Route as VisitRouteImport } from './routes/visit'
import { Route as ArchivesSlugRouteImport } from './routes/archives.$slug'
import { Route as RegisterSuccessRouteImport } from './routes/register.success'
import { Route as TournamentsSlugRouteImport } from './routes/tournaments.$slug'
import { Route as PayloadAdminIndexRouteImport } from './routes/_payload/admin.index'
import { Route as PayloadAdminSplatRouteImport } from './routes/_payload/admin.$'
import { Route as PayloadApiSplatRouteImport } from './routes/_payload/api.$'
import { Route as ApiRegistrationCheckoutRouteImport } from './routes/api.registration.checkout'
import { Route as ApiStripeWebhookRouteImport } from './routes/api.stripe.webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PayloadRoute = PayloadRouteImport.update({
  id: '/_payload',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchivesRoute = ArchivesRouteImport.update({
  id: '/archives',
  path: '/archives',
  getParentRoute: () => rootRouteImport,
} as any)
const HallOfFameRoute = HallOfFameRouteImport.update({
  id: '/hall-of-fame',
  path: '/hall-of-fame',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalLeaguesRoute = LocalLeaguesRouteImport.update({
  id: '/local-leagues',
  path: '/local-leagues',
  getParentRoute: () => rootRouteImport,
} as any)
const MotelRoute = MotelRouteImport.update({
  id: '/motel',
  path: '/motel',
  getParentRoute: () => rootRouteImport,
} as any)
const PitcherClassificationRoute = PitcherClassificationRouteImport.update({
  id: '/pitcher-classification',
  path: '/pitcher-classification',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsRoute = TournamentsRouteImport.update({
  id: '/tournaments',
  path: '/tournaments',
  getParentRoute: () => rootRouteImport,
} as any)
const UmpireRoute = UmpireRouteImport.update({
  id: '/umpire',
  path: '/umpire',
  getParentRoute: () => rootRouteImport,
} as any)
const UmpiresRoute = UmpiresRouteImport.update({
  id: '/umpires',
  path: '/umpires',
  getParentRoute: () => rootRouteImport,
} as any)
const VisitRoute = VisitRouteImport.update({
  id: '/visit',
  path: '/visit',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchivesSlugRoute = ArchivesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ArchivesRoute,
} as any)
const RegisterSuccessRoute = RegisterSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => RegisterRoute,
} as any)
const TournamentsSlugRoute = TournamentsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => TournamentsRoute,
} as any)
const PayloadAdminIndexRoute = PayloadAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => PayloadRoute,
} as any)
const PayloadAdminSplatRoute = PayloadAdminSplatRouteImport.update({
  id: '/admin/$',
  path: '/admin/$',
  getParentRoute: () => PayloadRoute,
} as any)
const PayloadApiSplatRoute = PayloadApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => PayloadRoute,
} as any)
const ApiRegistrationCheckoutRoute = ApiRegistrationCheckoutRouteImport.update({
  id: '/api/registration/checkout',
  path: '/api/registration/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/archives': typeof ArchivesRouteWithChildren
  '/hall-of-fame': typeof HallOfFameRoute
  '/local-leagues': typeof LocalLeaguesRoute
  '/motel': typeof MotelRoute
  '/pitcher-classification': typeof PitcherClassificationRoute
  '/register': typeof RegisterRouteWithChildren
  '/rules': typeof RulesRoute
  '/tournaments': typeof TournamentsRouteWithChildren
  '/umpire': typeof UmpireRoute
  '/umpires': typeof UmpiresRoute
  '/visit': typeof VisitRoute
  '/archives/$slug': typeof ArchivesSlugRoute
  '/register/success': typeof RegisterSuccessRoute
  '/tournaments/$slug': typeof TournamentsSlugRoute
  '/admin/$': typeof PayloadAdminSplatRoute
  '/api/$': typeof PayloadApiSplatRoute
  '/api/registration/checkout': typeof ApiRegistrationCheckoutRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/admin/': typeof PayloadAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/archives': typeof ArchivesRouteWithChildren
  '/hall-of-fame': typeof HallOfFameRoute
  '/local-leagues': typeof LocalLeaguesRoute
  '/motel': typeof MotelRoute
  '/pitcher-classification': typeof PitcherClassificationRoute
  '/register': typeof RegisterRouteWithChildren
  '/rules': typeof RulesRoute
  '/tournaments': typeof TournamentsRouteWithChildren
  '/umpire': typeof UmpireRoute
  '/umpires': typeof UmpiresRoute
  '/visit': typeof VisitRoute
  '/archives/$slug': typeof ArchivesSlugRoute
  '/register/success': typeof RegisterSuccessRoute
  '/tournaments/$slug': typeof TournamentsSlugRoute
  '/admin/$': typeof PayloadAdminSplatRoute
  '/api/$': typeof PayloadApiSplatRoute
  '/api/registration/checkout': typeof ApiRegistrationCheckoutRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/admin': typeof PayloadAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_payload': typeof PayloadRouteWithChildren
  '/archives': typeof ArchivesRouteWithChildren
  '/hall-of-fame': typeof HallOfFameRoute
  '/local-leagues': typeof LocalLeaguesRoute
  '/motel': typeof MotelRoute
  '/pitcher-classification': typeof PitcherClassificationRoute
  '/register': typeof RegisterRouteWithChildren
  '/rules': typeof RulesRoute
  '/tournaments': typeof TournamentsRouteWithChildren
  '/umpire': typeof UmpireRoute
  '/umpires': typeof UmpiresRoute
  '/visit': typeof VisitRoute
  '/archives/$slug': typeof ArchivesSlugRoute
  '/register/success': typeof RegisterSuccessRoute
  '/tournaments/$slug': typeof TournamentsSlugRoute
  '/_payload/admin/$': typeof PayloadAdminSplatRoute
  '/_payload/api/$': typeof PayloadApiSplatRoute
  '/api/registration/checkout': typeof ApiRegistrationCheckoutRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/_payload/admin/': typeof PayloadAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/archives'
    | '/hall-of-fame'
    | '/local-leagues'
    | '/motel'
    | '/pitcher-classification'
    | '/register'
    | '/rules'
    | '/tournaments'
    | '/umpire'
    | '/umpires'
    | '/visit'
    | '/archives/$slug'
    | '/register/success'
    | '/tournaments/$slug'
    | '/admin/$'
    | '/api/$'
    | '/api/registration/checkout'
    | '/api/stripe/webhook'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/archives'
    | '/hall-of-fame'
    | '/local-leagues'
    | '/motel'
    | '/pitcher-classification'
    | '/register'
    | '/rules'
    | '/tournaments'
    | '/umpire'
    | '/umpires'
    | '/visit'
    | '/archives/$slug'
    | '/register/success'
    | '/tournaments/$slug'
    | '/admin/$'
    | '/api/$'
    | '/api/registration/checkout'
    | '/api/stripe/webhook'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_payload'
    | '/archives'
    | '/hall-of-fame'
    | '/local-leagues'
    | '/motel'
    | '/pitcher-classification'
    | '/register'
    | '/rules'
    | '/tournaments'
    | '/umpire'
    | '/umpires'
    | '/visit'
    | '/archives/$slug'
    | '/register/success'
    | '/tournaments/$slug'
    | '/_payload/admin/$'
    | '/_payload/api/$'
    | '/api/registration/checkout'
    | '/api/stripe/webhook'
    | '/_payload/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PayloadRoute: typeof PayloadRouteWithChildren
  ArchivesRoute: typeof ArchivesRouteWithChildren
  HallOfFameRoute: typeof HallOfFameRoute
  LocalLeaguesRoute: typeof LocalLeaguesRoute
  MotelRoute: typeof MotelRoute
  PitcherClassificationRoute: typeof PitcherClassificationRoute
  RegisterRoute: typeof RegisterRouteWithChildren
  RulesRoute: typeof RulesRoute
  TournamentsRoute: typeof TournamentsRouteWithChildren
  UmpireRoute: typeof UmpireRoute
  UmpiresRoute: typeof UmpiresRoute
  VisitRoute: typeof VisitRoute
  ApiRegistrationCheckoutRoute: typeof ApiRegistrationCheckoutRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_payload': {
      id: '/_payload'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PayloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archives': {
      id: '/archives'
      path: '/archives'
      fullPath: '/archives'
      preLoaderRoute: typeof ArchivesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hall-of-fame': {
      id: '/hall-of-fame'
      path: '/hall-of-fame'
      fullPath: '/hall-of-fame'
      preLoaderRoute: typeof HallOfFameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/local-leagues': {
      id: '/local-leagues'
      path: '/local-leagues'
      fullPath: '/local-leagues'
      preLoaderRoute: typeof LocalLeaguesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/motel': {
      id: '/motel'
      path: '/motel'
      fullPath: '/motel'
      preLoaderRoute: typeof MotelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pitcher-classification': {
      id: '/pitcher-classification'
      path: '/pitcher-classification'
      fullPath: '/pitcher-classification'
      preLoaderRoute: typeof PitcherClassificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments': {
      id: '/tournaments'
      path: '/tournaments'
      fullPath: '/tournaments'
      preLoaderRoute: typeof TournamentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/umpire': {
      id: '/umpire'
      path: '/umpire'
      fullPath: '/umpire'
      preLoaderRoute: typeof UmpireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/umpires': {
      id: '/umpires'
      path: '/umpires'
      fullPath: '/umpires'
      preLoaderRoute: typeof UmpiresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visit': {
      id: '/visit'
      path: '/visit'
      fullPath: '/visit'
      preLoaderRoute: typeof VisitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archives/$slug': {
      id: '/archives/$slug'
      path: '/$slug'
      fullPath: '/archives/$slug'
      preLoaderRoute: typeof ArchivesSlugRouteImport
      parentRoute: typeof ArchivesRoute
    }
    '/register/success': {
      id: '/register/success'
      path: '/success'
      fullPath: '/register/success'
      preLoaderRoute: typeof RegisterSuccessRouteImport
      parentRoute: typeof RegisterRoute
    }
    '/tournaments/$slug': {
      id: '/tournaments/$slug'
      path: '/$slug'
      fullPath: '/tournaments/$slug'
      preLoaderRoute: typeof TournamentsSlugRouteImport
      parentRoute: typeof TournamentsRoute
    }
    '/_payload/admin/': {
      id: '/_payload/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof PayloadAdminIndexRouteImport
      parentRoute: typeof PayloadRoute
    }
    '/_payload/admin/$': {
      id: '/_payload/admin/$'
      path: '/admin/$'
      fullPath: '/admin/$'
      preLoaderRoute: typeof PayloadAdminSplatRouteImport
      parentRoute: typeof PayloadRoute
    }
    '/_payload/api/$': {
      id: '/_payload/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof PayloadApiSplatRouteImport
      parentRoute: typeof PayloadRoute
    }
    '/api/registration/checkout': {
      id: '/api/registration/checkout'
      path: '/api/registration/checkout'
      fullPath: '/api/registration/checkout'
      preLoaderRoute: typeof ApiRegistrationCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PayloadRouteChildren {
  PayloadAdminSplatRoute: typeof PayloadAdminSplatRoute
  PayloadApiSplatRoute: typeof PayloadApiSplatRoute
  PayloadAdminIndexRoute: typeof PayloadAdminIndexRoute
}

const PayloadRouteChildren: PayloadRouteChildren = {
  PayloadAdminSplatRoute: PayloadAdminSplatRoute,
  PayloadApiSplatRoute: PayloadApiSplatRoute,
  PayloadAdminIndexRoute: PayloadAdminIndexRoute,
}

const PayloadRouteWithChildren =
  PayloadRoute._addFileChildren(PayloadRouteChildren)

interface ArchivesRouteChildren {
  ArchivesSlugRoute: typeof ArchivesSlugRoute
}

const ArchivesRouteChildren: ArchivesRouteChildren = {
  ArchivesSlugRoute: ArchivesSlugRoute,
}

const ArchivesRouteWithChildren = ArchivesRoute._addFileChildren(
  ArchivesRouteChildren,
)

interface RegisterRouteChildren {
  RegisterSuccessRoute: typeof RegisterSuccessRoute
}

const RegisterRouteChildren: RegisterRouteChildren = {
  RegisterSuccessRoute: RegisterSuccessRoute,
}

const RegisterRouteWithChildren = RegisterRoute._addFileChildren(
  RegisterRouteChildren,
)

interface TournamentsRouteChildren {
  TournamentsSlugRoute: typeof TournamentsSlugRoute
}

const TournamentsRouteChildren: TournamentsRouteChildren = {
  TournamentsSlugRoute: TournamentsSlugRoute,
}

const TournamentsRouteWithChildren = TournamentsRoute._addFileChildren(
  TournamentsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PayloadRoute: PayloadRouteWithChildren,
  ArchivesRoute: ArchivesRouteWithChildren,
  HallOfFameRoute: HallOfFameRoute,
  LocalLeaguesRoute: LocalLeaguesRoute,
  MotelRoute: MotelRoute,
  PitcherClassificationRoute: PitcherClassificationRoute,
  RegisterRoute: RegisterRouteWithChildren,
  RulesRoute: RulesRoute,
  TournamentsRoute: TournamentsRouteWithChildren,
  UmpireRoute: UmpireRoute,
  UmpiresRoute: UmpiresRoute,
  VisitRoute: VisitRoute,
  ApiRegistrationCheckoutRoute: ApiRegistrationCheckoutRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
